meta(charset:"utf-8") newLine()
meta(name:"viewport", content:"width=device-width, initial-scale=1, shrink-to-fit=no") newLine()
title("${config.blog_title}") newLine()
link(rel:"stylesheet", href:"${config.site_contextPath}css/vendor/bootstrap.min.css") newLine()
link(rel:"stylesheet", href:"${config.site_contextPath}css/app.css") newLine()
link(rel:"stylesheet", href:"${config.site_contextPath}css/vendor/highlightjs/default.css") newLine()
script(src:"${config.site_contextPath}js/vendor/highlight.pack.js","") newLine()
script("hljs.initHighlightingOnLoad();") newLine()
