name: CD
on: [push]

jobs:
  build:
    runs-on: ubuntu-18.04
    container: 
      image: docker://javastreets/jbake:2.6.4 
      options: --user 1001
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: build
        run: jbake -b
      - name: upload ftp
        uses: sebastianpopp/git-ftp-action@releases/v3
        with:
          host: ftp://ftpx.forpsi.com/subdoms/blog
          user: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          syncroot: output
