name: CD
on: [push]

jobs:
  build:
    runs-on: ubuntu-18.04
    container: 
      image: docker://javastreets/jbake:2.6.4 
      options: --user 1001
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: build
        run: jbake -b
  deploy:
    runs-on: ubuntu-18.04
    needs: build
    container: 
      image: docker://takatakato/ncftp
      env: 
        FTP_USERNAME: "${{ secrets.FTP_USERNAME }}"
        FTP_PASSWORD: "${{ secrets.FTP_PASSWORD }}"
        FTP_TEST: "Test"
    steps:
      - name: upload ftp
        run: echo ${FTP_TEST}
        #run: ncftpput -u ${FTP_USERNAME} -p ${FTP_PASSWORD} -v -m -R -r 10 ftpx.forpsi.com /subdoms/blog/ /data/.
