name: CD
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container: 
      image: docker://jbake/jbake:2.6.7
      options: --user 1001
    steps:
      - name: Checkout sources
        uses: actions/checkout@v1
      - name: Build blog
        run: jbake -b
      - name: Upload output
        uses: actions/upload-artifact@v1
        with:
          name: jbake-output
          path: output
  deploy:
    runs-on: ubuntu-18.04
    needs: build
    container: 
      image: docker://mwienk/docker-lftp
      env: 
        FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
        FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
    steps:
      - name: Download output
        uses: actions/download-artifact@v1
        with:
          name: jbake-output
      - name: Upload ftp
        run: lftp -e "mirror -R jbake-output /subdoms/blog" -u "${FTP_USERNAME}","${FTP_PASSWORD}" ftpx.forpsi.com
