name: CD
on: [push]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-18.04
    container: 
      image: docker://javastreets/jbake:2.6.4 
      options: --user 1001
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: build
        run: jbake -b
  deploy:
    runs-on: ubuntu-18.04
    needs: [build]
    steps:
      - name: Upload ftp
        uses: sebastianpopp/ftp-action@releases/v2
        with:
          host: "ftpx.forpsi.com"
          user: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          localDir: "/output"
          remoteDir: "/subdoms/blog"
