# This is a basic workflow to help you get started with Actions

name: CI
on: [push]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: build
        run: jbake -h
      - uses: docker://javastreets/jbake:2.6.4
